packages:
  - backend
  - agent
allowBuilds:
  cbor-extract: set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - cbor-extract
  - esbuild
patchedDependencies:
  '@justscale/postgres@0.1.5': patches/@justscale__postgres@0.1.5.patch
